name: angle

on:
  push:
    branches: [ "main" ]

jobs:


  build-angle-win64:
    runs-on: windows-latest
    env:
      DEPOT_TOOLS_WIN_TOOLCHAIN: 0
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
    - name: get-depot-tools
      run: git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
    - name: fetch-angle
      run: |
        mkdir angle
        cd angle
        ..\depot_tools\fetch angle
    - name: setup-makefiles
      working-directory: angle
      run: |
        mkdir out\Release
        copy ..\skia-win.args out\Release\args.gn
        ..\depot_tools\gn gen out\Release
    - name: build
      working-directory: angle
      run: |
        ..\depot_tools\autoninja -C out/Release libEGL
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        # Artifact name
        name: angle-shared-win64
        path: |
          angle/out/Release/libEGL.dll.lib
          angle/out/Release/libGLESv2.dll.lib
          angle/out/Release/libEGL.dll
          angle/out/Release/libGLESv2.dll
          angle/out/Release/d3dcompiler*
          

  build-angle-linux64:
    runs-on: ubuntu-latest
    env:
      DEPOT_TOOLS_WIN_TOOLCHAIN: 0
    steps:
    - name: get-depot-tools
      run: |
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
        echo "${GITHUB_WORKSPACE}/depot_tools" >> $GITHUB_PATH
    - name: fetch-angle
      run: |
        mkdir angle
        cd angle
        fetch angle
    - name: install-dependencies
      run: ./build/install-build-deps.sh
      working-directory: angle
    - name: setup-makefiles
      working-directory: angle
      run: |
        mkdir -p out/Release
        cp ../skia-linux.args out/Release/args.gn
        gn gen out/Release
    - name: build
      working-directory: angle
      run: |
        autoninja -C out/Release libEGL
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        # Artifact name
        name: angle-shared-linux64
        path: |
          angle/out/Release/libEGL.*
          angle/out/Release/libGLESv2.*
